config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: "admin" do
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" }
    scope module: "admin" do
      root "dashboard#index", as: "admin_dashboard"
      resources :profiles
      resources :categories, as: "admin_categories"
      resources :articles, as: "admin_articles"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index" # Main blog homepage
  get "errors/not_found"
  get "/about", to: "pages#about"
  resources :categories, only: %i[show], as: "category", path: "category"
  resources :articles, only: %i[index show]
  resources :authors, only: %i[show], path: "author"
  resources :contacts, only: %i[new create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  match "*path", to: "errors#not_found", via: :all, constraints: lambda { |req|
    !req.path.start_with?("/assets", "/rails/active_storage")
  }
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  slug       :string
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_articles_on_author_id  (author_id)
#  index_articles_on_slug       (slug) UNIQUE
#

class Article < ApplicationRecord
  extend FriendlyId

  before_save :set_published_at, if: :status_changed_to_published?

  ARTICLE_FEATURED_IMAGE_TYPES = [:webp].freeze

  belongs_to :author, class_name: "Admin", foreign_key: "author_id"
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  has_many :article_read_counts, dependent: :destroy

  has_one_attached :featured_image, dependent: :destroy
  has_rich_text :content

  enum :status, { published: "published", draft: "draft", archived: "archived" }, default: :draft

  validates :title, :author, :slug, :content, presence: true
  validates :title, uniqueness: true
  validates :title, length: { maximum: 60, too_long: "%{count} characters is the maximum allowed" }
  validates :featured_image, content_type: ARTICLE_FEATURED_IMAGE_TYPES, size: { less_than_or_equal_to: 500.kilobyte }

  friendly_id :title, use: %i[slugged history finders]

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  scope :descending_order, -> { order(created_at: :desc) }

  def self.ransackable_attributes(auth_object = nil)
    ["title", "slug"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["categories"]
  end

  private

  def status_changed_to_published?
    status_changed? && published?
  end

  def set_published_at
    self.published_at ||= Time.current
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @pagy, @articles = pagy(Article.includes(:author).descending_order, limit: 15)
  end

  def show
  end

  def new
    @article = current_admin.articles.build
  end

  def create
    @article = current_admin.articles.build(article_params)
    if @article.save
      redirect_to [ :admin, @article ], notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @article, :manage?
  end

  def update
    authorize @article, :manage?
    if @article.update(article_params)
      redirect_to [ :admin, @article ], notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @article, :manage?
    @article.destroy
    redirect_to admin_articles_url, notice: "Article was successfully destroyed."
  end

  private

  def set_article
    @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_articles_path, alert: "Article Not found."
  end

  def article_params
    params.require(:article).permit(:title, :featured_image, :content, :status, category_ids: [])
  end

  def pundit_user
    current_admin
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  def index
    @q = Article.ransack(params[:q])
    @pagy, @articles = pagy(@q.result(distinct: true).includes(:author, :article_categories).published.descending_order, limit: 18)

    # Only redirect if this was a search AND there are no results
    if @articles.empty? && params[:q].present?
      flash[:alert] = "No article found for your search criteria."
      redirect_to root_path
    end

  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
  end

  def show
    @related_articles = Article.published.where.not(id: @article.id).descending_order.limit(4)
    @article.article_read_counts.create(read_at: Time.current)
    @article.increment!(:read_count)

    image_url = @article.featured_image.attached? ? url_for(@article.featured_image) : nil
    set_meta_tags title: @article.title, description: @article.content.to_s, og: {
      title: :title, description: :description, image: image_url, url: article_url(@article)
    }, type: "article"
  end

  private

  def set_article
    @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, notice: "Article not found."
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def hero_text = [
    {
      title: "Answers to My Coding Curiosities",
      description: "Welcome to my coding journal! I share answers to challenges I’ve faced, keeping track of lessons learned while helping beginners and curious coders."
    }
  ]

  def menu_links = [
    {
      item: "About",
      path: about_path
    },
    {
      item: "Contact",
      path: new_contact_path
    }
  ]

  def services = [
    {
      icon: "/icons/web.svg", # A combined icon for both services
      title: "Web & Mobile Development",
      href: "https://jeanemmanuelcadet.com/services#web-mobile",
      description:
        "I provide top-notch development services for both web and mobile platforms. From dynamic landing pages and sophisticated web applications to sleek and robust mobile apps for Android and iOS, I deliver custom solutions that captivate and engage your audience.",
      price: "20" # Adjust price to reflect combined services, if applicable
    },
    {
      icon: "/icons/api.svg",
      title: "API development",
      href: "https://jeanemmanuelcadet.com/services#api",
      description:
        "Integrate and streamline your systems with secure, scalable APIs designed to meet your specific requirements.",
      price: "25"
    },
    {
      icon: "/icons/database.svg",
      title: "Database design and management",
      href: "https://jeanemmanuelcadet.com/services#database",
      description:
        "Design and manage robust databases that efficiently store and organize your critical data, ensuring optimal performance and reliability.",
      price: "35"
    }
  ]

  def show_updated_date(article_date)
    article_date.updated_at.strftime("%b %d, %Y")
  end

  def article_created_date(article_created_date)
    article_created_date.created_at.strftime("%b %d, %Y")
  end

  def article_published_date(article_published_date)
    article_published_date.published_at.strftime("%b %d, %Y")
  end

  def tailwind_class_for(flash_type)
    case flash_type
    when "notice" then "bg-green-50 text-green-900 shadow rounded"
    when "alert" then "bg-red-50 text-red-900 shadow rounded"
    end
  end

  def reading_time(article)
    words_per_minute = 200
    word_count = article.body.to_s.split(/\s+/).size
    time = (word_count / words_per_minute.to_f).ceil

    if time == 1
      "#{time} minute"
    else
      "#{time} minutes"
    end
  end
end

app/views/admin/articles/_article.html.erb
<% if articles.present? %>
  <!-- Current Admin Articles Table-->
  <section class="bg-gray-50 dark:bg-gray-900 antialiased">
    <div class="mx-auto">
      <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
        <div class="overflow-x-auto">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">Cover</th>
              <th scope="col" class="px-6 py-3 w-80">Title</th>
              <th scope="col" class="px-6 py-3 w-80">Slug</th>
              <th scope="col" class="px-6 py-3">Author</th>
              <th scope="col" class="px-6 py-3">Status</th>
              <th scope="col" class="px-6 py-3 w-40">Created Date</th>
              <th scope="col" class="px-6 py-3 w-40">Published On</th>
              <th scope="col" class="px-6 py-3 text-center">Action</th>
            </tr>
            </thead>
            <tbody>
            <% articles.each do |article| %>
              <tr class="border-b dark:border-gray-700 border-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700">
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= render "layouts/shared/featured_image", resource: article, other_classes: "w-16 h-16 max-w-full max-h-full rounded" %>
                </td>
                <td class="px-4 py-3">
                  <%= link_to article.title, article_path(article), class: "hover:underline" %>
                </td>
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= link_to article.slug, article_url(article, host: "lvh.me", port: 3000), target: "_blank", class: " hover:underline" %>
                </td>
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= link_to article.author.name, profile_path(article.author), class: " hover:underline" %>
                </td>
                <td class="px-4 py-3 font-medium text-white whitespace-nowrap">
                  <span class="px-3 py-1 rounded-full <%= article_status_color(article.status.humanize) %>">
                    <%= article.status.humanize %>
                  </span>
                </td>
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= article_created_date(article) %>
                </td>
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <% if article.published_at.present? %>
                    <%= article_published_date(article) %>
                  <% else %>
                    —
                  <% end %>
                </td>
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <div class="flex items-center justify-center space-x-4">
                    <% if policy(article).manage? %>
                      <%= link_to edit_admin_article_path(article), class: "py-1 px-3 flex items-center text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" do %>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 -ml-0.5" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                          <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"/>
                          <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"/>
                        </svg>
                        Edit
                      <% end %>
                    <% end %>
                    <%= link_to admin_article_path(article), class: "py-1 px-3 flex items-center text-sm font-medium text-center text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" fill="currentColor" class="w-4 h-4 mr-2 -ml-0.5">
                        <path d="M12 15a3 3 0 100-6 3 3 0 000 6z"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M1.323 11.447C2.811 6.976 7.028 3.75 12.001 3.75c4.97 0 9.185 3.223 10.675 7.69.12.362.12.752 0 1.113-1.487 4.471-5.705 7.697-10.677 7.697-4.97 0-9.186-3.223-10.675-7.69a1.762 1.762 0 010-1.113zM17.25 12a5.25 5.25 0 11-10.5 0 5.25 5.25 0 0110.5 0z"/>
                      </svg>
                      Preview
                    <% end %>
                    <% if policy(article).manage? %>
                      <%= link_to admin_article_path(article), data: { turbo_confirm: "Are you sure you want to delete this article", turbo_method: :delete }, class: "flex items-center text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-3 py-1 text-center dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900" do %>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 -ml-0.5" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"/>
                        </svg>
                        Delete
                      <% end %>
                    <% end %>

                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
            <tfoot class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">Cover</th>
              <th scope="col" class="px-6 py-3 w-80">Title</th>
              <th scope="col" class="px-6 py-3 w-80">Slug</th>
              <th scope="col" class="px-6 py-3">Author</th>
              <th scope="col" class="px-6 py-3">Status</th>
              <th scope="col" class="px-6 py-3 w-40">Created Date</th>
              <th scope="col" class="px-6 py-3 w-40">Published On</th>
              <th scope="col" class="px-6 py-3 text-center">Action</th>
            </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </section>
<% else %>
  <%= render "layouts/shared/null_state", resource_name: "article", resource_path: new_admin_article_path %>
<% end %>
<!-- End Current Admin Articles Table-->

app/views/admin/articles/_form.html.erb
<section class="articles_form">
  <div class="lg:py-16">

    <%= form_with model: @article do |form| %>

      <!--      Display errors-->
      <div class="mb-5">
        <% if form.object.errors.any? %>
          <div class="p-4 border border-red-500 bg-red-100 rounded-md">
            <% form.object.errors.full_messages.each do |message| %>
              <p class="text-base text-red-600 dark:text-red-500"><%= message %></p>
            <% end %>
          </div>
        <% end %>
      </div>

      <!--      Article Title-->
      <div class="my-10">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-input", required: true, placeholder: "Enter article title", autofocus: true %>
      </div>

      <!--      File Upload-->
      <div class="my-10">
        <%= form.label "Add a featured Image", class: "form-label", for: "file_input" %>

        <div class="my-5">
          <% if @article.persisted? && @article.featured_image.attached? %>
            <%= image_tag @article.featured_image.variant(resize_to_limit: [300, 300]), class: "my-5 rounded" %>
          <% end %>
        </div>
        <%= form.file_field :featured_image, accept: "image/webp", direct_upload: true, class: "form-input", id: "file_input" %>
        <p class="text-sm text-gray-500 mt-1">Only <strong>.webp</strong> images are allowed. Please upload an optimized
          WebP file.</p>
      </div>

      <div class="my-10">
        <%= form.label :status, class: "form-label" %>
        <%= form.select :status, Article.statuses.keys.map { |status| [status.humanize, status] }, {}, class: "form-input" %>
      </div>

      <div class="my-10">
        <%= form.label "Categories", class: "form-label" %>
        <div class="space-x-4">
          <%= form.collection_checkboxes :category_ids, Category.all, :id, :name, {}, { multiple: true, class: "checkbox" } %>
        </div>
      </div>

      <!--      Write Content-->
      <div class="my-10 w-full">
        <%= form.label "Write an article", class: "form-label" %>
        <%= form.rich_text_area :content, required: true, placeholder: "Write an article...", class: "form-textarea" %>
      </div>

      <!--      Submit button-->
      <div class="space-x-3">
        <%= form.submit class: "button" %>
        <% if @article.persisted? %>
          <%= link_to "Cancel", admin_article_path(@article), class: "outline-button" %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/admin/articles/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Edit Article</h1>
  <%= render "admin/articles/form" %>
</div>

app/views/admin/articles/index.html.erb
<div class="flex justify-between items-center">
  <h1 class="h1 !mb-0">Articles</h1>
  <%= link_to "New Article", new_admin_article_path, class: "button" %>
</div>

<%= render "layouts/admin_shared/articles_tab", resources: @articles.published, draft_resources: @articles.draft, archived_resources: @articles.archived %>

app/views/admin/articles/new.html.erb
<div class="container mx-auto">
  <h1 class="font-bold text-4xl">Create Article</h1>
  <%= render "admin/articles/form" %>
</div>

app/views/admin/articles/show.html.erb
<% if policy(@article).manage? %>
  <div>
    <%= link_to "Edit Article", edit_admin_article_path(@article), class: "button" %>
  </div>
<% end %>

<%= render "layouts/admin_shared/base/hr" %>

<%= render 'layouts/show_article_template' %>