config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: "admin" do
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" }
    scope module: "admin" do
      root "dashboard#index", as: "admin_dashboard"
      resources :profiles
      resources :categories, as: "admin_categories"
      resources :articles, as: "admin_articles"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index" # Main blog homepage
  get "errors/not_found"
  get "/about", to: "pages#about"
  resources :categories, only: %i[show], as: "category", path: "category"
  resources :articles, only: %i[index show]
  resources :authors, only: %i[show], path: "author"
  resources :contacts, only: %i[new create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  match "*path", to: "errors#not_found", via: :all, constraints: lambda { |req|
    !req.path.start_with?("/assets", "/rails/active_storage")
  }
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController
  def index
    base_query = Article.published

    @articles = base_query.includes(:author).order(created_at: :desc).limit(6)
    @article_count = base_query.count
    @author_count = base_query.distinct.count(:author_id)
    @total_articles_read = base_query.sum(:read_count)
    @highest_read_count = base_query.maximum(:read_count)
    @most_read_articles = base_query.where(read_count: @highest_read_count).pluck(:title)
  end

  private

  def pundit_user
    current_admin
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<div class="flex flex-col md:flex-row items-center justify-between mb-5">
  <h1 class="h1">Dashboard</h1>
  <div class="flex flex-col md:flex-row items-center gap-x-5">
    <div class="flex flex-wrap gap-3 items-center md:space-x-5">
      <div class="w-full flex items-center gap-3 space-x-1 md:block md:w-auto">
        <%= link_to "New Article", new_admin_article_path, class: "button !w-full text-center" %>
        <%= link_to "List Articles", admin_articles_path, class: "outline-button !w-full text-center" %>
      </div>

      <div class="w-full flex items-center gap-3 space-x-1 md:block md:w-auto">
        <%= link_to "New Categories", new_admin_category_path, class: "button !w-full text-center" %>
        <%= link_to "List Categories", admin_categories_path, class: "outline-button !w-full text-center" %>
      </div>
      <% if policy(:admin).super_admin? %>
        <div class="w-full flex items-center gap-3 space-x-3 md:block md:w-auto">
          <%= link_to "New user account", new_profile_path, class: "button !w-full text-center" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="flex md:space-x-10 flex-col md:flex-row gap-5">
  <div class="p-7 md:w-80 rounded-lg shadow-md bg-[#FEEEF1] dark:bg-gray-800">
    <%= render "layouts/admin_shared/base/icons/article" %>
    <div>
      <p class="p md:!text-lg font-semibold">Total articles</p>
      <h3 class="text-xl md:text-4xl dark:text-white font-extrabold mb-3"><%= @article_count %></h3>
    </div>
  </div>

  <div class="p-7 md:w-80 rounded-lg shadow-md bg-[#FEF2DC] dark:bg-gray-800">
    <%= render "layouts/admin_shared/base/icons/profile_icon" %>
    <div>
      <p class="p md:!text-lg font-semibold">Total authors</p>
      <h3 class="text-xl md:text-4xl dark:text-white font-extrabold mb-3"><%= @author_count %></h3>
    </div>
  </div>

  <div class="p-7 md:w-80 rounded-lg shadow-md bg-[#D9FAE7] dark:bg-gray-800">
    <%= render "layouts/admin_shared/base/icons/read_icon" %>
    <div>
      <p class="p md:!text-lg font-semibold">Article reads</p>
      <h3 class="text-xl md:text-4xl dark:text-white font-extrabold mb-3"><%= number_to_human(@total_articles_read, units: { thousand: 'K', million: 'M', billion: 'B', trillion: 'T' }, format: "%n%u") %></h3>
    </div>
  </div>

  <div class="p-7 md:w-80 rounded-lg shadow-md bg-[#D4DFFB] dark:bg-gray-800">
    <%= render "layouts/admin_shared/base/icons/chart_icon" %>
    <div>
      <p class="p md:!text-lg font-semibold">Most article read</p>
      <h3 class="text-xl md:text-4xl dark:text-white font-extrabold mb-3"><%= number_to_human(@highest_read_count, units: { thousand: 'K', million: 'M', billion: 'B', trillion: 'T' }, format: "%n%u") %>
        Times</h3>
      <p class="p md:!text-[13px]">Article: <%= @most_read_articles.join(", ") %></p>
    </div>
  </div>
</div>
<%= render "layouts/admin_shared/base/hr" %>

<div>
  <h2 class="h2 !text-left">Reads Over the Last 3 Months</h2>
  <%= line_chart @articles.map { |article|
    { name: article.title, data: article.article_read_counts.group_by_day(:read_at, range: 3.month.ago..Time.current).count }
  }
  %>
</div>

<%= render "layouts/admin_shared/base/hr" %>

<div>
  <div class="flex items-center justify-between mb-5">
    <h2 class="h2 !text-left">6 Most Recent Articles</h2>
  </div>
  <%= render "admin/articles/article", articles: @articles %>
</div>