config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: "admin" do
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" }
    scope module: "admin" do
      root "dashboard#index", as: "admin_dashboard"
      resources :profiles
      resources :categories, as: "admin_categories"
      resources :articles, as: "admin_articles"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index" # Main blog homepage
  get "errors/not_found"
  get "/about", to: "pages#about"
  resources :categories, only: %i[show], as: "category", path: "category"
  resources :articles, only: %i[index show]
  resources :authors, only: %i[show], path: "author"
  resources :contacts, only: %i[new create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  match "*path", to: "errors#not_found", via: :all, constraints: lambda { |req|
    !req.path.start_with?("/assets", "/rails/active_storage")
  }
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < Admin::AdminController
  before_action :set_admin, only: %i[show edit update destroy]

  def index
    @admins = Admin.all
  end

  def show
    @articles = Article.includes(:author).descending_order
    @pagy, @admin_articles = pagy(@articles.where(author_id: @admin.id), limit: 15)
  end

  def new
    authorize current_admin, :super_admin?
    @admin = Admin.new
  end

  def create
    authorize current_admin, :super_admin?

    generated_password = Devise.friendly_token.first(8)
    @admin = Admin.new(set_params.merge(password: generated_password))

    if @admin.save
      AdminMailer.welcome_email(@admin, generated_password).deliver_later
      redirect_to profiles_path, notice: "Admin was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @admin, :manage?
  end

  def update
    authorize @admin, :manage?

    # Prevent regular admins from changing the role
    if current_admin.super_admin? && @admin.update(set_params)
      redirect_to profiles_path, notice: "Admin info was successfully updated."
    else
      # If a regular admin is trying to change the role, strip it from the params
      @admin.assign_attributes(set_params.except(:role))

      # Handle password update securely
      if password_params[:password].present? && password_params[:password_confirmation].present?
        # Check if the current password is correct before updating
        if @admin.update_with_password(password_params)
          bypass_sign_in(@admin) # Keep the admin logged in after password change
          redirect_to profiles_path, notice: "Profile updated successfully, password changed."
        else
          render :edit, status: :unprocessable_entity
        end
      else
        # If no password fields, update without changing password
        if @admin.update(set_params.except(:role))
          redirect_to profiles_path, notice: "Profile updated successfully."
        else
          render :edit, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    authorize @admin, :super_admin?
    @admin.destroy
    redirect_to profile_path, notice: "Account was successfully destroyed."
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def set_params
    params.require(:admin).permit(:email, :name, :bio, :profile_picture, :website, :whatsapp_number, :github, :linkedin, :facebook, :instagram, :role)
  end

  def password_params
    params.require(:admin).permit(:current_password, :password, :password_confirmation)
  end

  def pundit_user
    current_admin
  end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/views/admin/profiles/_admin.html.erb
<% if admins.present? %>
  <section class="bg-gray-50 dark:bg-gray-900 antialiased">
    <div class="mx-auto">
      <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
        <div class="overflow-x-auto">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">Profile Picture</th>
              <th scope="col" class="px-6 py-3 w-80">Name</th>
              <th scope="col" class="px-6 py-3 w-80">Role</th>
              <th scope="col" class="px-6 py-3 w-40">Date created</th>
              <th scope="col" class="px-6 py-3 text-center">Action</th>
            </tr>
            </thead>
            <tbody>
            <% admins.each do |admin| %>
              <tr class="border-b dark:border-gray-700 border-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700">
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= render "layouts/shared/profile_picture", resource: admin, other_classes: "w-16 max-w-full max-h-full rounded" %>
                </td>
                <td class="px-4 py-3">
                  <%= link_to admin.name, profile_path(admin), class: "hover:underline" %>
                </td>
                <td class="px-4 py-3 font-medium text-white whitespace-nowrap">
                <span class="px-3 py-1 rounded-full <%= role_color(admin.role.humanize) %>">
                  <%= admin.role.humanize %>
                </span>
                </td>
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= admin.created_at.strftime("%b %d, %Y") %>
                </td>
                <td class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <div class="flex items-center justify-center space-x-4">
                    <% if policy(admin).manage? %>
                      <%= link_to edit_profile_path(admin), class: "py-2 px-3 flex items-center text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" do %>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 -ml-0.5" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                          <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"/>
                          <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"/>
                        </svg>
                        Edit
                      <% end %>
                    <% end %>
                    <%= link_to profile_path(admin), class: "py-2 px-3 flex items-center text-sm font-medium text-center text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" fill="currentColor" class="w-4 h-4 mr-2 -ml-0.5">
                        <path d="M12 15a3 3 0 100-6 3 3 0 000 6z"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M1.323 11.447C2.811 6.976 7.028 3.75 12.001 3.75c4.97 0 9.185 3.223 10.675 7.69.12.362.12.752 0 1.113-1.487 4.471-5.705 7.697-10.677 7.697-4.97 0-9.186-3.223-10.675-7.69a1.762 1.762 0 010-1.113zM17.25 12a5.25 5.25 0 11-10.5 0 5.25 5.25 0 0110.5 0z"/>
                      </svg>
                      Preview
                    <% end %>
                    <% if policy(admin).super_admin? %>
                      <%= link_to profile_path(admin), data: { turbo_confirm: "Are you sure you want to delete this account", turbo_method: :delete }, class: "flex items-center text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-3 py-2 text-center dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900" do %>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-2 -ml-0.5" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"/>
                        </svg>
                        Delete
                      <% end %>
                    <% end %>

                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
            <tfoot class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">Profile Picture</th>
              <th scope="col" class="px-6 py-3 w-80">Name</th>
              <th scope="col" class="px-6 py-3 w-80">Role</th>
              <th scope="col" class="px-6 py-3 w-40">Date created</th>
              <th scope="col" class="px-6 py-3 text-center">Action</th>
            </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </section>
<% else %>
  <%= render "layouts/shared/null_state", resource_name: "users" %>
<% end %>

app/views/admin/profiles/_form.html.erb
<%= form_with model: @admin, url: @admin.new_record? ? profiles_path : profile_path(@admin), class: "space-y-4" do |f| %>

  <div class="mb-5">
    <% if f.object.errors.any? %>
      <div class="p-4 border border-red-500 bg-red-100 rounded-md">
        <% f.object.errors.full_messages.each do |message| %>
          <p class="text-base text-red-600 dark:text-red-500"><%= message %></p>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="flex flex-col">
    <%= render "layouts/shared/profile_picture", resource: @admin, other_classes: "w-20 h-20 rounded-full" %>
    <%= f.label :profile_picture, class: "form-label mt-4" %>
    <%= f.file_field :profile_picture, accept: "image/webp", direct_upload: true, class: "form-input" %>
    <p class="text-sm text-gray-500 mt-1">Only <strong>.webp</strong> images are allowed. Please upload an optimized
      WebP file.</p>
  </div>

  <div class="flex flex-col">
    <%= f.label :email, class: "form-label" %>
    <%= f.text_field :email, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :password, class: "form-label" %>
    <%= f.text_field :password, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :password_confirmation, class: "form-label" %>
    <%= f.text_field :password_confirmation, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :bio, class: "form-label" %>
    <%= f.text_area :bio, cols: "50", rows: "5", class: "form-input" %>
  </div>

  <% if policy(@admin).super_admin? %>
    <div class="flex flex-col">
      <%= f.label :role, class: "form-label" %>
      <%= f.select :role, Admin.roles.keys.map { |role| [role.humanize, role] }, {}, class: "form-input" %>
    </div>
  <% end %>

  <div class="flex flex-col">
    <%= f.label :website, class: "form-label" %>
    <%= f.text_field :website, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :whatsapp_number, class: "form-label" %>
    <%= f.text_field :whatsapp_number, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :github, class: "form-label" %>
    <%= f.text_field :github, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :facebook, class: "form-label" %>
    <%= f.text_field :facebook, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :linkedin, class: "form-label" %>
    <%= f.text_field :linkedin, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :instagram, class: "form-label" %>
    <%= f.text_field :instagram, class: "form-input" %>
  </div>

  <div class="space-x-3">
    <%= f.submit class: "button" %>
    <% if @admin.persisted? %>
      <%= link_to "Cancel", profile_path(@admin), class: "outline-button" %>
    <% end %>
  </div>
<% end %>

app/views/admin/profiles/edit.html.erb
<h1 class="h1">Update Information</h1>

<%= form_with model: @admin, url: profile_path, method: :patch, class: "space-y-4" do |f| %>

  <div class="mb-5">
    <% if f.object.errors.any? %>
      <div class="p-4 border border-red-500 bg-red-100 rounded-md">
        <% f.object.errors.full_messages.each do |message| %>
          <p class="text-base text-red-600 dark:text-red-500"><%= message %></p>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="flex flex-col">
    <%= render "layouts/shared/profile_picture", resource: @admin, other_classes: "w-20 h-20 rounded-full" %>
    <%= f.label :profile_picture, class: "form-label mt-4" %>
    <%= f.file_field :profile_picture, accept: "image/webp", direct_upload: true, class: "form-input" %>
    <p class="text-sm text-gray-500 mt-1">Only <strong>.webp</strong> images are allowed. Please upload an optimized
      WebP file.</p>
  </div>

  <div class="flex flex-col">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, required: true, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :bio, class: "form-label" %>
    <%= f.text_area :bio, cols: "50", rows: "5", class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label "Current Password", class: "form-label" %>
    <%= f.password_field :current_password, class: "form-input" %>
    <small>(Required to update password)</small>
  </div>

  <div class="flex flex-col">
    <%= f.label "New Password", class: "form-label" %>
    <%= f.password_field :password, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label "Confirm New Password", class: "form-label" %>
    <%= f.password_field :password_confirmation, class: "form-input" %>
  </div>

  <% if policy(@admin).super_admin? %>
    <div class="flex flex-col">
      <%= f.label :role, class: "form-label" %>
      <%= f.select :role, Admin.roles.keys.map { |role| [role.humanize, role] }, {}, { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
    </div>
  <% end %>

  <div class="flex flex-col">
    <%= f.label :website, class: "form-label" %>
    <%= f.text_field :website, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :whatsapp_number, class: "form-label" %>
    <%= f.text_field :whatsapp_number, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :github, class: "form-label" %>
    <%= f.text_field :github, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :facebook, class: "form-label" %>
    <%= f.text_field :facebook, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :linkedin, class: "form-label" %>
    <%= f.text_field :linkedin, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :instagram, class: "form-label" %>
    <%= f.text_field :instagram, class: "form-input" %>
  </div>

  <div class="space-x-3">
    <%= f.submit "Update Information", class: "button" %>
    <% if @admin.persisted? %>
      <%= link_to "Cancel", profiles_path, class: "outline-button" %>
    <% end %>
  </div>
<% end %>

app/views/admin/profiles/index.html.erb
<div class="flex justify-between items-center p-5">
  <h1 class="h1 !mb-0">Users</h1>
  <% if policy(:admin).super_admin? %>
    <%= link_to "New user account", new_profile_path, class: "button" %>
  <% end %>
</div>

<%= render "layouts/admin_shared/base/hr" %>

<%= render "admin/profiles/admin", admins: @admins %>

app/views/admin/profiles/new.html.erb
<h1 class="h1">Create account</h1>

<%= form_with model: @admin, url: profiles_path, method: :post, class: "space-y-5" do |f| %>

  <div class="mb-5">
    <% if f.object.errors.any? %>
      <div class="p-4 border border-red-500 bg-red-100 rounded-md">
        <% f.object.errors.full_messages.each do |message| %>
          <p class="text-base text-red-600 dark:text-red-500"><%= message %></p>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="flex flex-col">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, required: true, class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= f.label :email, class: "form-label" %>
    <%= f.text_field :email, required: true, class: "form-input" %>
  </div>

  <% if policy(@admin).super_admin? %>
    <div class="flex flex-col">
      <%= f.label :role, class: "form-label" %>
      <%= f.select :role, Admin.roles.keys.map { |role| [role.humanize, role] }, {}, { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" } %>
    </div>
  <% end %>

  <div class="flex flex-col">
    <%= f.label :bio, class: "form-label" %>
    <%= f.text_area :bio, cols: "50", rows: "5", class: "form-input" %>
  </div>

  <div class="flex flex-col">
    <%= render "layouts/shared/profile_picture", resource: @admin, other_classes: "w-20 h-20 rounded-full" %>
    <%= f.label :profile_picture, class: "form-label mt-4" %>
    <%= f.file_field :profile_picture, accept: Admin::ADMIN_PROFILE_PICTURE_TYPES.join(","), direct_upload: true, class: "form-input" %>
  </div>

  <div class="space-x-3">
    <%= f.submit "Create account", class: "button" %>
  </div>
<% end %>

app/views/admin/profiles/show.html.erb
<div>
  <div class="flex items-center justify-between flex-wrap">
    <div class="lg:w-[40%]">
      <h1 class="h1 dark:text-white">
        <%= @admin.name %>
      </h1>
      <p class="dark:text-white">
        <%= @admin.bio %>
      </p>
      <div class="mt-3">
        <%= render "layouts/shared/socials", resource: @admin %>
      </div>
    </div>
    <% if policy(@admin).manage? %>
      <%= link_to "Edit", edit_profile_path(@admin), class: "button w-full md:w-auto text-center" %>
    <% end %>
  </div>
</div>

<%= render "layouts/admin_shared/base/hr" %>

<h2 class="h2 !text-left">Articles</h2>

<%= render "layouts/admin_shared/articles_tab", resources: @admin_articles.published, draft_resources: @admin_articles.draft, archived_resources: @admin_articles.archived %>