config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: "admin" do
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" }
    scope module: "admin" do
      root "dashboard#index", as: "admin_dashboard"
      resources :profiles
      resources :categories, as: "admin_categories"
      resources :articles, as: "admin_articles"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index" # Main blog homepage
  get "errors/not_found"
  get "/about", to: "pages#about"
  resources :categories, only: %i[show], as: "category", path: "category"
  resources :articles, only: %i[index show]
  resources :authors, only: %i[show], path: "author"
  resources :contacts, only: %i[new create]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  match "*path", to: "errors#not_found", via: :all, constraints: lambda { |req|
    !req.path.start_with?("/assets", "/rails/active_storage")
  }
end

app/views/layouts/admin_shared/_articles_tab.html.erb
<div class="mb-4 border-b border-gray-200 dark:border-gray-700">
  <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="default-tab" data-tabs-toggle="#default-tab-content" role="tablist">
    <li class="me-2" role="presentation">
      <button class="inline-block p-4 border-b-2 rounded-t-lg cursor-pointer" id="published-tab" data-tabs-target="#published" type="button" role="tab" aria-controls="published" aria-selected="false">Published</button>
    </li>
    <li class="me-2" role="presentation">
      <button class="inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 cursor-pointer" id="draft-tab" data-tabs-target="#draft" type="button" role="tab" aria-controls="draft" aria-selected="false">Draft</button>
    </li>
    <li role="presentation">
      <button class="inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 cursor-pointer" id="archived-tab" data-tabs-target="#archived" type="button" role="tab" aria-controls="archived" aria-selected="false">Archived</button>
    </li>
  </ul>
</div>

<div id="default-tab-content">
  <div class="hidden rounded-lg bg-gray-50 dark:bg-gray-800" id="published" role="tabpanel" aria-labelledby="published-tab">
    <%= render "admin/articles/article", articles: resources %>
    <div class="px-5 pb-5">
      <%= render "layouts/admin_shared/pagy" %>
    </div>
  </div>
  <div class="hidden rounded-lg bg-gray-50 dark:bg-gray-800" id="draft" role="tabpanel" aria-labelledby="draft-tab">
    <%= render "admin/articles/article", articles: draft_resources %>
  </div>
  <div class="hidden rounded-lg bg-gray-50 dark:bg-gray-800" id="archived" role="tabpanel" aria-labelledby="archived-tab">
    <%= render "admin/articles/article", articles: archived_resources %>
  </div>
</div>

app/views/layouts/admin_shared/_basic_layout.html.erb
<div class="rounded-lg mx-auto flex flex-wrap lg:justify-between pb-20">
  <div class="w-full lg:w-2/3 lg:mr-5 mb-5 lg:mb-0 px-5 mt-10">
    <%= yield :primary_content %>
  </div>
  <div class="w-full lg:w-1/4 rounded-3xl px-5 mt-10">
    <%= yield :secondary_content %>
  </div>
</div>

app/views/layouts/admin_shared/_nav.html.erb
<nav class="bg-primary w-full h-15 px-10 flex items-center">
  <div class="w-full">
    <% if admin_signed_in? %>
      <div class="flex items-center justify-end space-x-3">
        <div data-controller="dropdown" class="relative h-10">
          <button type="button" data-action="dropdown#toggle click@window->dropdown#hide">
          </button>
          <div
            data-dropdown-target="menu"
            class="hidden transition transform origin-top-right absolute right-0 bg-white w-40 px-5 py-2 space-y-2 rounded shadow"
            data-transition-enter-from="opacity-0 scale-95"
            data-transition-enter-to="opacity-100 scale-100"
            data-transition-leave-from="opacity-100 scale-100"
            data-transition-leave-to="opacity-0 scale-95"
          >
            <ul class="space-y-2 divide-y divide-gray-100">
              <li>
                <%= link_to "Profile", profile_path(current_admin), class: "dropdown_link" %>
              </li>
              <li>
                <%= link_to "Log out", destroy_admin_session_path, method: :delete, data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "dropdown_link" %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</nav>



<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo"/>
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
    </a>
    <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <span class="sr-only">Open user menu</span>
        <%= image_tag current_admin.profile_picture, class: "w-10 rounded-full cursor-pointer" %>

      </button>
      <!-- Dropdown menu -->
      <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow-sm dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
        <div class="px-4 py-3">
          <span class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
          <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">name@flowbite.com</span>
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Dashboard</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Earnings</a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign
              out</a>
          </li>
        </ul>
      </div>
      <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
      </button>
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
      <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="#" class="block py-2 px-3 text-white bg-blue-700 rounded-sm md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Home</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Pricing</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin_shared/_pagy.html.erb
<div class="container mx-auto my-10">
  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/layouts/admin_shared/admin.html.erb
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <title><%= content_for(:title) || "CodeCurious | Dashboard" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="robots" content="noindex, nofollow">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config / routes.rb too!) %>
  <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%#= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
  <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.turbo.min.js"></script>

  <script>
    // On page load or when changing themes, best to add inline in `head` to avoid FOUC
    if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark')
    }
  </script>
</head>

<body class="bg-gray-100 dark:bg-gray-900 dark:text-white text-gray-900 antialiased">
<div class="wrapper">
  <div class="flash">
    <%= render "layouts/shared/flash_messages" %>
  </div>
  <%= render "layouts/admin_shared/base/sidebar/sidebar" %>
  <div class="p-4 sm:ml-64">
    <div class="p-4 rounded-lg dark:border-gray-700 mt-14">
      <%= yield %>
    </div>
  </div>
  <div class="sm:ml-64">
    <%= render "layouts/admin_shared/base/footer" %>
  </div>
</div>
</body>
</html>